### ISSUE TITLE
Error building css after startup

### ISSUE THREAD

**Issue by marcomd** [justalever/kickoff_tailwind#23]
The error is generated by the command:
`yarn build:css --watch`

that generates the error:
`error Command "build:css" not found.`

To solve I added in the package.json :

```yaml
  "scripts": {
    "build": "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds",
    "build:css": "tailwindcss -i ./app/assets/stylesheets/application.tailwind.css -o ./app/assets/builds/application.css"
  }
```
